{
 "title": "SmokePing",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "SmokePing 1.1.1.1",
   "type": "histogram",
   "description": "1.1.1.1",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(smokeping_response_duration_seconds_bucket{ip=\"1.1.1.1\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SmokePing 1.1.1.1",
   "type": "heatmap",
   "description": "1.1.1.1",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(smokeping_response_duration_seconds_bucket{ip=\"1.1.1.1\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 31, "w": 2, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smokeping_requests_total", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 31, "w": 1, "x": 23, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smokeping_send_errors_total", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Dropped pings 1.1.1.1",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "increase(smokeping_response_duration_seconds_count{ip=\"1.1.1.1\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(smokeping_requests_total{ip=\"1.1.1.1\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SmokePing 8.8.8.8",
   "type": "histogram",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(smokeping_response_duration_seconds_bucket{ip=\"8.8.8.8\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SmokePing 8.8.8.8",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(smokeping_response_duration_seconds_bucket{ip=\"8.8.8.8\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Dropped pings 8.8.8.8",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 28 },
   "targets": [
    {
     "expr": "increase(smokeping_response_duration_seconds_count{ip=\"8.8.8.8\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(smokeping_requests_total{ip=\"8.8.8.8\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}